---
- name: Install prometheus-node-exporter from apt
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
    update_cache: true

- name: Enable and start prometheus-node-exporter service
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
    daemon_reload: true
