apiVersion: homelab.gibbsgreatly.xyz/v1alpha1
kind: EdgeManifest
metadata:
  name: harbor-edge
  stack: harbor-stack
  annotations:
    repo.auth.oidc.client_id_env: HARBOR_OIDC_CLIENT_ID
    repo.auth.oidc.client_secret_env: HARBOR_OIDC_CLIENT_SECRET
spec:
  routes:
    - name: harbor
      host: harbor.lab.gibbsgreatly.xyz
      backend:
        type: url
        url: http://${LAB_IP_HARBOR}
      dns:
        enabled: true
        target: ${LAB_IP_PROXY}
        ttl: 5m
      tls:
        resolver: letsencrypt
      auth:
        mode: oidc
