sonar.projectKey=stevedwray_proxmox-homelab
sonar.organization=stevedwray
sonar.projectName=proxmox-homelab
sonar.sources=.
sonar.exclusions=**/.terraform/**,**/terraform/.terraform/**,**/.terragrunt-cache/**,**/_legacy/**,**/_archive/**,.env,.env.*,**/netbox-stack/configuration/**
sonar.host.url=https://sonarcloud.io
# sonar.branch.name is passed dynamically in CI via -Dsonar.branch.name=${{ github.ref_name }}
