sonar.projectKey=stevedwray_proxmox-homelab
sonar.organization=stevedwray
sonar.projectName=proxmox-homelab
sonar.sources=.
sonar.exclusions=**/.terraform/**,**/terraform/.terraform/**,**/.terragrunt-cache/**,**/_legacy/**,**/_archive/**,.env,.env.*,**/netbox-stack/configuration/**,docs/**
sonar.coverage.exclusions=**
sonar.issue.ignore.multicriteria=harborHttpSecurityScan,harborHttpSignatureGate,harborHttpSigningProof
sonar.issue.ignore.multicriteria.harborHttpSecurityScan.ruleKey=githubactions:S5332
sonar.issue.ignore.multicriteria.harborHttpSecurityScan.resourceKey=.github/workflows/security-scan.yml
sonar.issue.ignore.multicriteria.harborHttpSignatureGate.ruleKey=githubactions:S5332
sonar.issue.ignore.multicriteria.harborHttpSignatureGate.resourceKey=.github/workflows/signature-gate.yml
sonar.issue.ignore.multicriteria.harborHttpSigningProof.ruleKey=githubactions:S5332
sonar.issue.ignore.multicriteria.harborHttpSigningProof.resourceKey=.github/workflows/supply-chain-signing-proof.yml
sonar.host.url=https://sonarcloud.io
# sonar.branch.name is passed dynamically in CI via -Dsonar.branch.name=${{ github.ref_name }}
