services:
  whoami:
    image: ${REGISTRY_HOST}/dockerhub/traefik/whoami:latest
    container_name: test-docker-whoami
    ports:
      - "8080:80"
    restart: unless-stopped

  nginx:
    image: ${REGISTRY_HOST}/dockerhub/library/nginx:alpine
    container_name: test-docker-nginx
    ports:
      - "80:80"
    restart: unless-stopped
