# test-docker — Nginx test stack deployed via Portainer API
hostname: test-docker
ip_address: "192.168.1.52/24"
dns_server: "192.168.1.1"
vmid: 131
cores: 2
memory: 2048
rootfs_size: 8
rootfs_storage: infrastructure-containers
ostemplate: "storage-template:vztmpl/debian-13.1-2-docker-template.tar.gz"

# Deployment
ansible_playbook: "deploy-stack"
portainer_agent: true
app_stack_name: "test-docker"
