apiVersion: homelab.gibbsgreatly.xyz/v1alpha1
kind: EdgeManifest
metadata:
  name: netbox-edge
  stack: netbox-stack
spec:
  routes:
    - name: netbox
      host: netbox.${LAB_DOMAIN}
      backend:
        type: url
        url: http://${LAB_IP_NETBOX}:8080
      dns:
        enabled: true
        target: ${LAB_IP_PROXY}
        ttl: 5m
      tls:
        resolver: letsencrypt
      auth:
        mode: forwardAuth
