apiVersion: homelab.gibbsgreatly.xyz/v1alpha1
kind: EdgeManifest
metadata:
  name: cse-panel-edge
  stack: cse-panel-stack
spec:
  routes:
    - name: cse-panel
      host: cse-panel.${LAB_DOMAIN}
      backend:
        type: url
        url: http://${LAB_IP_CSE_PANEL}:8000
      dns:
        enabled: true
        target: ${LAB_IP_PROXY}
        ttl: 5m
      tls:
        resolver: letsencrypt
      auth:
        mode: forwardAuth
    - name: cse-panel-flower
      host: cse-panel-flower.${LAB_DOMAIN}
      backend:
        type: url
        url: http://${LAB_IP_CSE_PANEL}:5555
      dns:
        enabled: true
        target: ${LAB_IP_PROXY}
        ttl: 5m
      tls:
        resolver: letsencrypt
      auth:
        mode: forwardAuth
