all:
  children:
    proxmox:
      children:
        proxmox_production:
          hosts:
            pve.gibbsgreatly.xyz:
              ansible_host: "{{ lookup('env', 'PROXMOX_PRODUCTION_HOST_IP') | default('pve.gibbsgreatly.xyz', true) }}"
              ansible_user: root
              ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') | default('~/.ssh/id_ed25519') }}"

        proxmox_testbed:
          hosts:
            pve-test.gibbsgreatly.xyz:
              ansible_host: "{{ lookup('env', 'PROXMOX_TESTBED_HOST_IP') | default('pve-test.gibbsgreatly.xyz', true) }}"
              ansible_user: root
              ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') | default('~/.ssh/id_ed25519') }}"
              pmx_enable_nftables_firewall: true

      vars:
        # Common Proxmox variables (apply to ALL Proxmox hosts)
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    # Debian template builder containers
    debian_template_builder:
      hosts:
        debian_builder:
          ansible_host: "{{ ansible_host_ip_map.debian_template_builder }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') | default('~/.ssh/id_ed25519') }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
