---
# terraform/ansible/shared-roles/docker_base/handlers/main.yml

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  listen: "restart docker"
