services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.11ubu2604-ls47
    container_name: media-stack-lab-jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${LAB_DOMAIN}
    volumes:
      - jellyfin-config:/config
      - /nas-media/video/movies:/movies
      - /nas-media/video/tv:/tv
      - /nas-media/music:/music
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    group_add:
      - "44"
      - "104"
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: media-stack-lab-immich-server
    user: "1000:1000"
    environment:
      - IMMICH_CONFIG_FILE=/immich-config.json
      - DB_HOSTNAME=database
      - DB_PORT=5432
      - DB_USERNAME=immich
      - DB_PASSWORD=${MEDIA_STACK_LAB_DB_PASSWORD}
      - DB_DATABASE_NAME=immich
    volumes:
      - /nas-media/immich-photos:/data
      - /nas-media/pictures:/nas-photos-import:ro
      - /etc/localtime:/etc/localtime:ro
      - ./immich-config.json:/immich-config.json:ro
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: media-stack-lab-immich-machine-learning
    volumes:
      - model-cache:/cache
    restart: unless-stopped

  redis:
    image: docker.io/valkey/valkey:9@sha256:3acc0687f2a2e1091fae6450d7842dd658c941338cf0a873ddd9e14b9e4ea4dd
    container_name: media-stack-lab-redis
    restart: unless-stopped

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: media-stack-lab-database
    environment:
      - POSTGRES_PASSWORD=${MEDIA_STACK_LAB_DB_PASSWORD}
      - POSTGRES_USER=immich
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - immich-db-data:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped

  cadvisor:
    image: ${REGISTRY_HOST}/ghcr/google/cadvisor:v0.60.5
    container_name: media-stack-lab-cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro

volumes:
  jellyfin-config:
  model-cache:
  immich-db-data:
