---
rsyslog_forward_target_host: "{{ lookup('env', 'LAB_IP_MONITORING') | mandatory('LAB_IP_MONITORING env var is required') }}"
rsyslog_forward_target_port: "5140"
rsyslog_inbound_enabled: false
rsyslog_inbound_tcp_port: "514"
rsyslog_inbound_udp_port: "514"
