# terraform/ansible/shared-roles/portainer_api/defaults/main.yml

---
portainer_api_server_ip: >-
  {{
    portainer_server_ip
    | default(lookup('env', 'LAB_IP_PORTAINER'), true)
    | mandatory('portainer_server_ip var or LAB_IP_PORTAINER env var is required')
  }}
portainer_api_server_port: "9000"

portainer_api_admin_user: "admin"
# TF_VAR_portainer_admin_password is the canonical name in OpenBao/with-secrets
portainer_api_admin_password: >-
  {{
    lookup('env', 'TF_VAR_portainer_admin_password')
    | default(lookup('env', 'PORTAINER_ADMIN_PASSWORD'), true)
    | mandatory('TF_VAR_portainer_admin_password environment variable is not set')
  }}

portainer_api_endpoint_name: "{{ inventory_hostname }}"
portainer_api_agent_ip: "{{ ansible_host }}"
portainer_api_agent_port: "9001"
