# terraform/management-stack/ansible/playbook.yml
---

- name: Apply base Docker configuration to all hosts
  hosts: all
  remote_user: root
  become: true
  roles:
    - ../../ansible/shared-roles/docker_base  # Updated path

- name: Deploy Portainer Server
  hosts: portainer_server
  remote_user: root
  become: true
  vars:
    portainer_container_name: "portainer"
    portainer_image: "portainer/portainer-ce:latest"
    portainer_port_http: "9000"
    portainer_port_https: "9443"
  roles:
    - portainer_server
