# File: management-stack/ansible/wait-for-ssh.yml

---
- name: Wait for SSH connection to be available
  hosts: management_stack
  gather_facts: false
  tasks:
    - name: Wait for SSH port
      ansible.builtin.wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: 22
        delay: 5      # Initial delay before the first check
        timeout: 120  # Total time to wait before failing
      delegate_to: localhost