apiVersion: homelab.gibbsgreatly.xyz/v1alpha1
kind: EdgeManifest
metadata:
  name: wazuh-edge
  stack: wazuh-stack
  annotations:
    repo.auth.oidc.client_id_env: WAZUH_OIDC_CLIENT_ID
    repo.auth.oidc.client_secret_env: WAZUH_OIDC_CLIENT_SECRET
spec:
  routes:
    - name: dashboard
      host: wazuh.${LAB_DOMAIN}
      backend:
        type: url
        url: http://${LAB_IP_WAZUH}:5601
      dns:
        enabled: true
        target: ${LAB_IP_PROXY}
        ttl: 5m
      tls:
        resolver: letsencrypt
      auth:
        mode: oidc
