apiVersion: homelab.gibbsgreatly.xyz/v1alpha1
kind: EdgeManifest
metadata:
  name: elasticsearch-edge
  stack: elasticsearch-stack
spec:
  routes:
    - name: kibana
      host: kibana.${LAB_DOMAIN}
      backend:
        type: url
        url: http://${LAB_IP_ELASTICSEARCH}:5601
      dns:
        enabled: true
        target: ${LAB_IP_PROXY}
        ttl: 5m
      tls:
        resolver: letsencrypt
      auth:
        mode: forwardAuth
