apiVersion: homelab.gibbsgreatly.xyz/v1alpha1
kind: EdgeManifest
metadata:
  name: monitoring-edge
  stack: monitoring-stack
spec:
  routes:
    - name: grafana
      host: grafana.lab.gibbsgreatly.xyz
      backend:
        type: url
        url: http://${LAB_IP_MONITORING}:3000
      dns:
        enabled: true
        target: ${LAB_IP_PROXY}
        ttl: 5m
      tls:
        resolver: letsencrypt
      auth:
        mode: oidc
